/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createGameResponseFromDiscriminatorValue, serializeCreateChallengeGameRequest, serializeGameResponse, type CreateChallengeGameRequest, type GameResponse } from '../../../../models/index.js';
// @ts-ignore
import { type WithGameItemRequestBuilder, WithGameItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/challenges/{challengeId}/games
 */
export interface GamesRequestBuilder extends BaseRequestBuilder<GamesRequestBuilder> {
    /**
     * Gets an item from the Frontend.api.challenges.item.games.item collection
     * @param gameId Unique identifier of the item
     * @returns {WithGameItemRequestBuilder}
     */
     byGameId(gameId: string) : WithGameItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<GameResponse[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<GameResponse[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<GameResponse>}
     */
     post(body: CreateChallengeGameRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<GameResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateChallengeGameRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const GamesRequestBuilderUriTemplate = "{+baseurl}/api/challenges/{challengeId}/games";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const GamesRequestBuilderNavigationMetadata: Record<Exclude<keyof GamesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byGameId: {
        requestsMetadata: WithGameItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["gameId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const GamesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: GamesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createGameResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: GamesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createGameResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateChallengeGameRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
