/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createGameResponseFromDiscriminatorValue, serializeGameResponse, serializeUpdateChallengeGameRequest, type GameResponse, type UpdateChallengeGameRequest } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/challenges/{challengeId}/games/{gameId}
 */
export interface WithGameItemRequestBuilder extends BaseRequestBuilder<WithGameItemRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<GameResponse>}
     */
     put(body: UpdateChallengeGameRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<GameResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: UpdateChallengeGameRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithGameItemRequestBuilderUriTemplate = "{+baseurl}/api/challenges/{challengeId}/games/{gameId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithGameItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: WithGameItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createGameResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeUpdateChallengeGameRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
