/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface ChallengeResponse extends Parsable {
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The shortId property
     */
    shortId?: string | null;
    /**
     * The username property
     */
    username?: string | null;
    /**
     * The year property
     */
    year?: number | null;
}
export interface CreateChallengeRequest extends Parsable {
    /**
     * The username property
     */
    username?: string | null;
    /**
     * The year property
     */
    year?: number | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ChallengeResponse}
 */
// @ts-ignore
export function createChallengeResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoChallengeResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateChallengeRequest}
 */
// @ts-ignore
export function createCreateChallengeRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateChallengeRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ErrorResponse_errors}
 */
// @ts-ignore
export function createErrorResponse_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoErrorResponse_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ErrorResponse}
 */
// @ts-ignore
export function createErrorResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoErrorResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateChallengeRequest}
 */
// @ts-ignore
export function createUpdateChallengeRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateChallengeRequest;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoChallengeResponse(challengeResponse: Partial<ChallengeResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { challengeResponse.id = n.getStringValue(); },
        "shortId": n => { challengeResponse.shortId = n.getStringValue(); },
        "username": n => { challengeResponse.username = n.getStringValue(); },
        "year": n => { challengeResponse.year = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateChallengeRequest(createChallengeRequest: Partial<CreateChallengeRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "username": n => { createChallengeRequest.username = n.getStringValue(); },
        "year": n => { createChallengeRequest.year = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoErrorResponse(errorResponse: Partial<ErrorResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "errors": n => { errorResponse.errors = n.getObjectValue<ErrorResponse_errors>(createErrorResponse_errorsFromDiscriminatorValue); },
        "message": n => { errorResponse.messageEscaped = n.getStringValue() ?? "One or more errors occurred!"; },
        "statusCode": n => { errorResponse.statusCode = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoErrorResponse_errors(errorResponse_errors: Partial<ErrorResponse_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateChallengeRequest(updateChallengeRequest: Partial<UpdateChallengeRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "year": n => { updateChallengeRequest.year = n.getNumberValue(); },
    }
}
/**
 * the dto used to send an error response to the client
 */
export interface ErrorResponse extends ApiError, Parsable {
    /**
     * the collection of errors for the current context
     */
    errors?: ErrorResponse_errors | null;
    /**
     * the message for the error response
     */
    messageEscaped?: string | null;
    /**
     * the http status code sent to the client. default is 400.
     */
    statusCode?: number | null;
}
/**
 * the collection of errors for the current context
 */
export interface ErrorResponse_errors extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeChallengeResponse(writer: SerializationWriter, challengeResponse: Partial<ChallengeResponse> | undefined | null = {}) : void {
    if (challengeResponse) {
        writer.writeStringValue("id", challengeResponse.id);
        writer.writeStringValue("shortId", challengeResponse.shortId);
        writer.writeStringValue("username", challengeResponse.username);
        writer.writeNumberValue("year", challengeResponse.year);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateChallengeRequest(writer: SerializationWriter, createChallengeRequest: Partial<CreateChallengeRequest> | undefined | null = {}) : void {
    if (createChallengeRequest) {
        writer.writeStringValue("username", createChallengeRequest.username);
        writer.writeNumberValue("year", createChallengeRequest.year);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeErrorResponse(writer: SerializationWriter, errorResponse: Partial<ErrorResponse> | undefined | null = {}) : void {
    if (errorResponse) {
        writer.writeObjectValue<ErrorResponse_errors>("errors", errorResponse.errors, serializeErrorResponse_errors);
        writer.writeStringValue("message", errorResponse.messageEscaped ?? "One or more errors occurred!");
        writer.writeNumberValue("statusCode", errorResponse.statusCode);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeErrorResponse_errors(writer: SerializationWriter, errorResponse_errors: Partial<ErrorResponse_errors> | undefined | null = {}) : void {
    if (errorResponse_errors) {
        writer.writeAdditionalData(errorResponse_errors.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateChallengeRequest(writer: SerializationWriter, updateChallengeRequest: Partial<UpdateChallengeRequest> | undefined | null = {}) : void {
    if (updateChallengeRequest) {
        writer.writeNumberValue("year", updateChallengeRequest.year);
    }
}
export interface UpdateChallengeRequest extends Parsable {
    /**
     * The year property
     */
    year?: number | null;
}
/* tslint:enable */
/* eslint-enable */
