/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface ChallengeResponse extends Parsable {
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The shortId property
     */
    shortId?: string | null;
    /**
     * The username property
     */
    username?: string | null;
    /**
     * The year property
     */
    year?: number | null;
}
export interface CreateChallengeGameRequest extends Parsable {
    /**
     * The year property
     */
    year?: number | null;
}
export interface CreateChallengeRequest extends Parsable {
    /**
     * The username property
     */
    username?: string | null;
    /**
     * The year property
     */
    year?: number | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ChallengeResponse}
 */
// @ts-ignore
export function createChallengeResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoChallengeResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateChallengeGameRequest}
 */
// @ts-ignore
export function createCreateChallengeGameRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateChallengeGameRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateChallengeRequest}
 */
// @ts-ignore
export function createCreateChallengeRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateChallengeRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ErrorResponse_errors}
 */
// @ts-ignore
export function createErrorResponse_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoErrorResponse_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ErrorResponse}
 */
// @ts-ignore
export function createErrorResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoErrorResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {GameResponse}
 */
// @ts-ignore
export function createGameResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoGameResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateChallengeRequest}
 */
// @ts-ignore
export function createUpdateChallengeRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateChallengeRequest;
}
/**
 * The deserialization information for the current model
 * @param ChallengeResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoChallengeResponse(challengeResponse: Partial<ChallengeResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { challengeResponse.id = n.getStringValue(); },
        "shortId": n => { challengeResponse.shortId = n.getStringValue(); },
        "username": n => { challengeResponse.username = n.getStringValue(); },
        "year": n => { challengeResponse.year = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateChallengeGameRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateChallengeGameRequest(createChallengeGameRequest: Partial<CreateChallengeGameRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "year": n => { createChallengeGameRequest.year = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateChallengeRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateChallengeRequest(createChallengeRequest: Partial<CreateChallengeRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "username": n => { createChallengeRequest.username = n.getStringValue(); },
        "year": n => { createChallengeRequest.year = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ErrorResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoErrorResponse(errorResponse: Partial<ErrorResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "errors": n => { errorResponse.errors = n.getObjectValue<ErrorResponse_errors>(createErrorResponse_errorsFromDiscriminatorValue); },
        "message": n => { errorResponse.messageEscaped = n.getStringValue() ?? "One or more errors occurred!"; },
        "statusCode": n => { errorResponse.statusCode = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ErrorResponse_errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoErrorResponse_errors(errorResponse_errors: Partial<ErrorResponse_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param GameResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoGameResponse(gameResponse: Partial<GameResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "name": n => { gameResponse.name = n.getStringValue(); },
        "shortId": n => { gameResponse.shortId = n.getStringValue(); },
        "status": n => { gameResponse.status = n.getStringValue(); },
        "year": n => { gameResponse.year = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpdateChallengeRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateChallengeRequest(updateChallengeRequest: Partial<UpdateChallengeRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "year": n => { updateChallengeRequest.year = n.getNumberValue(); },
    }
}
/**
 * the dto used to send an error response to the client
 */
export interface ErrorResponse extends ApiError, Parsable {
    /**
     * the collection of errors for the current context
     */
    errors?: ErrorResponse_errors | null;
    /**
     * the message for the error response
     */
    messageEscaped?: string | null;
    /**
     * the http status code sent to the client. default is 400.
     */
    statusCode?: number | null;
}
/**
 * the collection of errors for the current context
 */
export interface ErrorResponse_errors extends AdditionalDataHolder, Parsable {
}
export interface GameResponse extends Parsable {
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The shortId property
     */
    shortId?: string | null;
    /**
     * The status property
     */
    status?: string | null;
    /**
     * The year property
     */
    year?: number | null;
}
/**
 * Serializes information the current object
 * @param ChallengeResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeChallengeResponse(writer: SerializationWriter, challengeResponse: Partial<ChallengeResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!challengeResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("id", challengeResponse.id);
    writer.writeStringValue("shortId", challengeResponse.shortId);
    writer.writeStringValue("username", challengeResponse.username);
    writer.writeNumberValue("year", challengeResponse.year);
}
/**
 * Serializes information the current object
 * @param CreateChallengeGameRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateChallengeGameRequest(writer: SerializationWriter, createChallengeGameRequest: Partial<CreateChallengeGameRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createChallengeGameRequest || isSerializingDerivedType) { return; }
    writer.writeNumberValue("year", createChallengeGameRequest.year);
}
/**
 * Serializes information the current object
 * @param CreateChallengeRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateChallengeRequest(writer: SerializationWriter, createChallengeRequest: Partial<CreateChallengeRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createChallengeRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("username", createChallengeRequest.username);
    writer.writeNumberValue("year", createChallengeRequest.year);
}
/**
 * Serializes information the current object
 * @param ErrorResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeErrorResponse(writer: SerializationWriter, errorResponse: Partial<ErrorResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!errorResponse || isSerializingDerivedType) { return; }
    writer.writeObjectValue<ErrorResponse_errors>("errors", errorResponse.errors, serializeErrorResponse_errors);
    writer.writeStringValue("message", errorResponse.messageEscaped ?? "One or more errors occurred!");
    writer.writeNumberValue("statusCode", errorResponse.statusCode);
}
/**
 * Serializes information the current object
 * @param ErrorResponse_errors The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeErrorResponse_errors(writer: SerializationWriter, errorResponse_errors: Partial<ErrorResponse_errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!errorResponse_errors || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(errorResponse_errors.additionalData);
}
/**
 * Serializes information the current object
 * @param GameResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeGameResponse(writer: SerializationWriter, gameResponse: Partial<GameResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!gameResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("name", gameResponse.name);
    writer.writeStringValue("shortId", gameResponse.shortId);
    writer.writeStringValue("status", gameResponse.status);
    writer.writeNumberValue("year", gameResponse.year);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpdateChallengeRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateChallengeRequest(writer: SerializationWriter, updateChallengeRequest: Partial<UpdateChallengeRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!updateChallengeRequest || isSerializingDerivedType) { return; }
    writer.writeNumberValue("year", updateChallengeRequest.year);
}
export interface UpdateChallengeRequest extends Parsable {
    /**
     * The year property
     */
    year?: number | null;
}
/* tslint:enable */
/* eslint-enable */
