/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createChallengeResponseFromDiscriminatorValue, createErrorResponseFromDiscriminatorValue, serializeChallengeResponse, serializeCreateChallengeRequest, type ChallengeResponse, type CreateChallengeRequest, type ErrorResponse } from '../../models/index.js';
// @ts-ignore
import { type WithChallengeItemRequestBuilder, WithChallengeItemRequestBuilderNavigationMetadata, WithChallengeItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/challenges
 */
export interface ChallengesRequestBuilder extends BaseRequestBuilder<ChallengesRequestBuilder> {
    /**
     * Gets an item from the Frontend.api.challenges.item collection
     * @param challengeId Unique identifier of the item
     * @returns {WithChallengeItemRequestBuilder}
     */
     byChallengeId(challengeId: string) : WithChallengeItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ChallengeResponse[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ChallengeResponse[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ChallengeResponse>}
     * @throws {ErrorResponse} error when the service returns a 400 status code
     */
     post(body: CreateChallengeRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ChallengeResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateChallengeRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ChallengesRequestBuilderUriTemplate = "{+baseurl}/api/challenges";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ChallengesRequestBuilderNavigationMetadata: Record<Exclude<keyof ChallengesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byChallengeId: {
        requestsMetadata: WithChallengeItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithChallengeItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["challengeId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ChallengesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ChallengesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createChallengeResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: ChallengesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createChallengeResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateChallengeRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
