/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createChallengeResponseFromDiscriminatorValue, createErrorResponseFromDiscriminatorValue, serializeChallengeResponse, serializeUpdateChallengeRequest, type ChallengeResponse, type ErrorResponse, type UpdateChallengeRequest } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/challenges/{challengeId}
 */
export interface WithChallengeItemRequestBuilder extends BaseRequestBuilder<WithChallengeItemRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ChallengeResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ChallengeResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ChallengeResponse>}
     * @throws {ErrorResponse} error when the service returns a 400 status code
     */
     put(body: UpdateChallengeRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ChallengeResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: UpdateChallengeRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithChallengeItemRequestBuilderUriTemplate = "{+baseurl}/api/challenges/{challengeId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithChallengeItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithChallengeItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createChallengeResponseFromDiscriminatorValue,
    },
    put: {
        uriTemplate: WithChallengeItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createChallengeResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeUpdateChallengeRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
