@Backend_Api_HostAddress = https://localhost:7206

### Get all challenges

GET {{Backend_Api_HostAddress}}/api/challenges

### Create challenge

# @name createChallenge
POST {{Backend_Api_HostAddress}}/api/challenges
Content-Type: application/json

{
  "username": "Gaveluxe1",
  "year": 2026
}

### Get challenge

@id = {{createChallenge.response.body.shortId}}

GET {{Backend_Api_HostAddress}}/api/challenges/{{id}}
Accept: application/json

### Update challenge

@id = {{createChallenge.response.body.shortId}}

PUT {{Backend_Api_HostAddress}}/api/challenges/{{id}}
Content-Type: application/json

{
  "year": 2028
}

### Add game to challenge

@challengeId = {{createChallenge.response.body.shortId}}

POST {{Backend_Api_HostAddress}}/api/challenges/{{challengeId}}/games
Content-Type: application/json

{
  "name": "Mindseye",
  "year": 2025,
  "status": "Completed",
}

### Get all games by challenge id

@challengeId = {{createChallenge.response.body.shortId}}

GET {{Backend_Api_HostAddress}}/api/challenges/{{challengeId}}/games
Accept: application/json